IF OBJECT_ID('dbo.PermitRecords', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PermitRecords (
    ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PermitRecords PRIMARY KEY,
    PERMIT_NO NVARCHAR(50) NOT NULL,
    PERMIT_TYPE NVARCHAR(100) NULL,
    WORK_DESCRIPTION NVARCHAR(MAX) NULL,
    WORK_LOCATION NVARCHAR(500) NULL,
    RECEIVER_NAME NVARCHAR(200) NULL,
    CLEARANCE_FROM NVARCHAR(8) NULL,
    CLEARANCE_TILL NVARCHAR(8) NULL,
    CONTRACTOR_NAME NVARCHAR(300) NULL,
    LOCATION_CODE NVARCHAR(50) NOT NULL,
    LOCATION_NAME NVARCHAR(200) NOT NULL,
    PAGE_TOP FLOAT NULL,
    PAGE_LEFT FLOAT NULL,
    RECORD_SOURCE NVARCHAR(20) NOT NULL
      CONSTRAINT DF_PermitRecords_RecordSource DEFAULT 'EMAIL',
    EMAIL_UID NVARCHAR(200) NULL,
    CREATED_AT DATETIME2(0) NOT NULL
      CONSTRAINT DF_PermitRecords_CreatedAt DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'UX_PermitRecords_PermitNo'
    AND object_id = OBJECT_ID('dbo.PermitRecords')
)
BEGIN
  CREATE UNIQUE NONCLUSTERED INDEX UX_PermitRecords_PermitNo
    ON dbo.PermitRecords(PERMIT_NO);
END;
GO

IF NOT EXISTS (
  SELECT 1
  FROM sys.indexes
  WHERE name = 'IX_PermitRecords_Location_Created'
    AND object_id = OBJECT_ID('dbo.PermitRecords')
)
BEGIN
  CREATE NONCLUSTERED INDEX IX_PermitRecords_Location_Created
    ON dbo.PermitRecords(LOCATION_CODE, CREATED_AT);
END;
GO